---
ConnectionStrings:
  RedisConnectionString.off: localhost,abortConnect=false
  ElasticsearchConnectionString.off: http://localhost:9200/
  LdapConnectionString.off: ''

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://dev.exceptionless.io

# Metrics
MetricsServerName: 10.0.0.5

# Exceptionless Client Settings
ExceptionlessServerUrl: https://dev-api.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823

FacebookAppId: 395178683904310
GitHubAppId: 7ef1dd5bfbc4ccf7f5ef
GoogleAppId: enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com
MicrosoftAppId: 000000004C137E8B
SlackAppId: 34500115540.177239122322
StripePublishableApiKey: pk_test_nStD8zuwsiyVjPhfxxxMEFeE