version: 4.2.{build}
os: Visual Studio 2017
configuration: Release
clone_depth: 2

pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  JAVA_HOME: C:\Progra~1\Java\jdk1.8.0
  API_URL: https://#{api.hostheader}
  BUILD_REPO_URL:
    secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCUMQAue0lh2sYqQ/TQlDbwg==
  BUILD_APP_REPO_URL:
     secure: vuYBT6D5arel88+Py/H3nnMPd4hInIXvr2cwhJaZSSSvJnmg+9sX1P5+bTWaJskYpGztHVMg0Iq7hgUCMKjh23w8WBrutLiUsixRE0LBjroIVJaRsYG1okSko0fNKVOCyOLKGt19Qrk45/TrTFlGMQ==

init:
  - git config --global core.autocrlf true
  - git config --global user.email "builds@exceptionless.io"
  - git config --global user.name "AppVeyor CI"
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

before_build:
  - ps: .\build\Set-BuildVersion.ps1 -Version $env:APPVEYOR_BUILD_VERSION -Suffix $env:VERSION_SUFFIX

build_script:
  - dotnet publish -c Release

on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_test:
  - ps: .\build\Start-ElasticSearch.ps1

test_script:
  - ps: Push-Location .\tests\Exceptionless.Api.Tests
  - ps: dotnet test -c Release --no-build
  - ps: Pop-Location

after_test:
  - ps: .\build\Push-Artifacts.ps1

artifacts:
  - path: release\*.zip
    name: ReleaseArtifacts

before_deploy:
  - ps: .\build\Create-Release.ps1

deploy:
  provider: GitHub
  auth_token:
    secure: 0s81q7bweVLTFSOKxnIhan7el6bIFiN8HJ1kYJzOkeFXX7wgGSq9bs/rV53X9qpf
  artifact: ReleaseArtifacts
  draft: true
  on:
    branch: master
    appveyor_repo_tag: true

notifications:
  - provider: Slack
    channel: '#notifications'
    auth_token:
      secure: GniMpFE62HprSyQNQoej/VSBnxn2GNnTrca3BnF8+ikMdqduO4Ts4t297teZF6wDAmGwnOtXusctUla8+WxLFkIztvVCS2Z1RG/DvEDYoc0=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
