---
ConnectionStrings:
  RedisConnectionString.off: localhost,abortConnect=false
  ElasticsearchConnectionString.off: http://localhost:9200/

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://be.exceptionless.io

# Email
# SmtpFrom:Exceptionless <noreply@exceptionless.io>
# SmtpHost: domain.com
# SmtpPort: 587
# SmtpEncryption: StartTLS
# SmtpUser: user@domain.com
# SmtpPassword: ''

# Metrics
MetricsServerName: 10.0.0.5

# Exceptionless Client Settings
ExceptionlessServerUrl: https://collector.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823

SlackAppId: 34500115540.177239122322